### PR TITLE
Create a response proxy object

### PR DESCRIPTION
**Pull request by kkirby**
This is required because the original object, by spec, cannot be mutated. See #14

### CODE REVIEW

**Comment by niftylettuce** [comment]
thanks @kkirby !

**Comment by niftylettuce** [comment]
published in v1.1.2

**Comment by niftylettuce** [comment]
@kkirby I unpublished v1.1.2 - the tests failed - can you fix tests and submit another PR?

**Comment by kkirby** [comment]
@niftylettuce That's really weird. I ran the tests myself and they passed. Where do you see that the tests failed?

**Comment by niftylettuce** [comment]
weird, it said it failed, but now it works for me.  I published as v1.1.3, sorry and thanks @kkirby

**Pull request merged**
